# =============================================================================
# NOTE:
#   * Plugins are installed by the `github-pages` gem. Do not add any plugins
#     here, they may not work on GitHub Pages. See
#     https://pages.github.com/versions/ for available plugins.
# =============================================================================

# basic infor for GitHub pages
domain: quantom-collab.github.io
baseurl: "" # intentionally left blank

# markdown renderer
markdown: kramdown

# jekyll plugins that we want to use
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# jekyll-seo-tag condfigs and site meta
title: QuantOm SciDAC Collaboration
tagline: QuantOm SciDAC Collaboration
description: A Collaboration for Quantum Chromodynamics Nuclear Tomography
author: QuantOm
logo: /assets/img/logo_quantom_collab.png
locale: en_US

# grouping different types of posts
collections:
  # folder _news
  news:
    output: true
  # folder _pages
  pages:
    output: true

# default key-value pairs in the front matter for each category
defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"
      author: "QuantOm"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"


# SCSS compiler config
sass:
  style: compressed

# things not to include in the `_site` folder
exclude:
  - "template"
  - "old"
  - ".sass-cache"
  - ".jekyll-cache"
  - "gemfiles"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle"
  - "vendor/cache"
  - "vendor/gems"
  - "vendor/ruby"
  - "README.md"
